{% set name = "altair_tiles" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/altair_tiles-{{ version }}.tar.gz
  sha256: c262a00baad4f37966be9490fc014db0dd7c15c6e98c7cf3cfa5492abb867961

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - altair
    - xyzservices
    - mercantile

test:
  imports:
    - altair_tiles
  commands:
    - pip check
  requires:
    - pip

about:
  summary: 'You can use altair_tiles to add tiles from any xyz tile provider such as OpenStreetMap to your Altair chart.'
  home: https://github.com/altair-viz/altair_tiles
  dev_url: https://github.com/altair-viz/altair_tiles
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - binste
